# Generated by Django 5.0.6 on 2026-08-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('id_card', 'ID Card'), ('wallet', 'Wallet'), ('electronics', 'Electronics'), ('books', 'Books'), ('keys', 'Keys'), ('bag', 'Bag'), ('other', 'Other')], default='other', max_length=20)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=5)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='open', max_length=10)),
                ('location', models.CharField(help_text='Where it was lost/found', max_length=150)),
                ('date_occurred', models.DateField(help_text='Date the item was lost/found')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
