# Generated by Django 5.0.6 on 2026-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('returned', 'returned'), ('archived', 'archived')], default='open', max_length=10),
        ),
    ]
